apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  # - manifests/nginx-ingress
  - manifests/tmate
resources:
  - manifests/configuration.yaml
  - manifests/statefulset.yaml
  - manifests/service-account.yaml
  - manifests/cluster-role-binding.yaml
  - manifests/tilt-service.yaml
configMapGenerator:
- name: kubemacs-configuration
  behavior: merge
  literals:
  - TZ=Pacific/Auckland
  - GIT_EMAIL=ii@ii.coop
  - GIT_NAME=Hippie Hopper
  - INIT_DEFAULT_DIR=~
  - INIT_DEFAULT_REPOS_FOLDER=~/Projects
  - INIT_DEFAULT_REPOS=https://github.com/cncf/apisnoop https://github.com/kubernetes/kubernetes
  - INIT_ORG_FILE=~/Projects/apisnoop/deployments/k8s/xip.io/README.org:37
# configMapGenerator:
#   - name: kubemacs-options
#     env: kubemacs-options
